// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dm.proto

package dm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PageInfo struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{0}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageInfo) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type ManResp struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManResp) Reset()         { *m = ManResp{} }
func (m *ManResp) String() string { return proto.CompactTextString(m) }
func (*ManResp) ProtoMessage()    {}
func (*ManResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{2}
}

func (m *ManResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManResp.Unmarshal(m, b)
}
func (m *ManResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManResp.Marshal(b, m, deterministic)
}
func (m *ManResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManResp.Merge(m, src)
}
func (m *ManResp) XXX_Size() int {
	return xxx_messageInfo_ManResp.Size(m)
}
func (m *ManResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ManResp.DiscardUnknown(m)
}

var xxx_messageInfo_ManResp proto.InternalMessageInfo

func (m *ManResp) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

//
//下面是设备管理模块的消息
type LoginAuthReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientID             string   `protobuf:"bytes,3,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Ip                   string   `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Certificate          []byte   `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAuthReq) Reset()         { *m = LoginAuthReq{} }
func (m *LoginAuthReq) String() string { return proto.CompactTextString(m) }
func (*LoginAuthReq) ProtoMessage()    {}
func (*LoginAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{3}
}

func (m *LoginAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAuthReq.Unmarshal(m, b)
}
func (m *LoginAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAuthReq.Marshal(b, m, deterministic)
}
func (m *LoginAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAuthReq.Merge(m, src)
}
func (m *LoginAuthReq) XXX_Size() int {
	return xxx_messageInfo_LoginAuthReq.Size(m)
}
func (m *LoginAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAuthReq proto.InternalMessageInfo

func (m *LoginAuthReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAuthReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginAuthReq) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *LoginAuthReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *LoginAuthReq) GetCertificate() []byte {
	if m != nil {
		return m.Certificate
	}
	return nil
}

type AccessAuthReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ClientID             string   `protobuf:"bytes,3,opt,name=clientID,proto3" json:"clientID,omitempty"`
	Access               string   `protobuf:"bytes,4,opt,name=access,proto3" json:"access,omitempty"`
	Ip                   string   `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessAuthReq) Reset()         { *m = AccessAuthReq{} }
func (m *AccessAuthReq) String() string { return proto.CompactTextString(m) }
func (*AccessAuthReq) ProtoMessage()    {}
func (*AccessAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{4}
}

func (m *AccessAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessAuthReq.Unmarshal(m, b)
}
func (m *AccessAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessAuthReq.Marshal(b, m, deterministic)
}
func (m *AccessAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessAuthReq.Merge(m, src)
}
func (m *AccessAuthReq) XXX_Size() int {
	return xxx_messageInfo_AccessAuthReq.Size(m)
}
func (m *AccessAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AccessAuthReq proto.InternalMessageInfo

func (m *AccessAuthReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccessAuthReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *AccessAuthReq) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AccessAuthReq) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *AccessAuthReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ProductInfo struct {
	CreatedTime          int64                   `protobuf:"varint,1,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	ProductID            string                  `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	ProductName          string                  `protobuf:"bytes,3,opt,name=productName,proto3" json:"productName,omitempty"`
	AuthMode             int64                   `protobuf:"varint,4,opt,name=authMode,proto3" json:"authMode,omitempty"`
	DeviceType           int64                   `protobuf:"varint,5,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	CategoryID           int64                   `protobuf:"varint,6,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	NetType              int64                   `protobuf:"varint,7,opt,name=netType,proto3" json:"netType,omitempty"`
	DataProto            int64                   `protobuf:"varint,8,opt,name=dataProto,proto3" json:"dataProto,omitempty"`
	AutoRegister         int64                   `protobuf:"varint,9,opt,name=autoRegister,proto3" json:"autoRegister,omitempty"`
	Secret               string                  `protobuf:"bytes,10,opt,name=secret,proto3" json:"secret,omitempty"`
	Template             *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=template,proto3" json:"template,omitempty"`
	Description          *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	DevStatus            *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=devStatus,proto3" json:"devStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProductInfo) Reset()         { *m = ProductInfo{} }
func (m *ProductInfo) String() string { return proto.CompactTextString(m) }
func (*ProductInfo) ProtoMessage()    {}
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{5}
}

func (m *ProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductInfo.Unmarshal(m, b)
}
func (m *ProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductInfo.Marshal(b, m, deterministic)
}
func (m *ProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductInfo.Merge(m, src)
}
func (m *ProductInfo) XXX_Size() int {
	return xxx_messageInfo_ProductInfo.Size(m)
}
func (m *ProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProductInfo proto.InternalMessageInfo

func (m *ProductInfo) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *ProductInfo) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *ProductInfo) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *ProductInfo) GetAuthMode() int64 {
	if m != nil {
		return m.AuthMode
	}
	return 0
}

func (m *ProductInfo) GetDeviceType() int64 {
	if m != nil {
		return m.DeviceType
	}
	return 0
}

func (m *ProductInfo) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *ProductInfo) GetNetType() int64 {
	if m != nil {
		return m.NetType
	}
	return 0
}

func (m *ProductInfo) GetDataProto() int64 {
	if m != nil {
		return m.DataProto
	}
	return 0
}

func (m *ProductInfo) GetAutoRegister() int64 {
	if m != nil {
		return m.AutoRegister
	}
	return 0
}

func (m *ProductInfo) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *ProductInfo) GetTemplate() *wrapperspb.StringValue {
	if m != nil {
		return m.Template
	}
	return nil
}

func (m *ProductInfo) GetDescription() *wrapperspb.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ProductInfo) GetDevStatus() *wrapperspb.StringValue {
	if m != nil {
		return m.DevStatus
	}
	return nil
}

type ManageProductReq struct {
	Opt                  int64        `protobuf:"varint,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Info                 *ProductInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ManageProductReq) Reset()         { *m = ManageProductReq{} }
func (m *ManageProductReq) String() string { return proto.CompactTextString(m) }
func (*ManageProductReq) ProtoMessage()    {}
func (*ManageProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{6}
}

func (m *ManageProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManageProductReq.Unmarshal(m, b)
}
func (m *ManageProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManageProductReq.Marshal(b, m, deterministic)
}
func (m *ManageProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManageProductReq.Merge(m, src)
}
func (m *ManageProductReq) XXX_Size() int {
	return xxx_messageInfo_ManageProductReq.Size(m)
}
func (m *ManageProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ManageProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_ManageProductReq proto.InternalMessageInfo

func (m *ManageProductReq) GetOpt() int64 {
	if m != nil {
		return m.Opt
	}
	return 0
}

func (m *ManageProductReq) GetInfo() *ProductInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetProductInfoReq struct {
	ProductID            string    `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	Page                 *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetProductInfoReq) Reset()         { *m = GetProductInfoReq{} }
func (m *GetProductInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetProductInfoReq) ProtoMessage()    {}
func (*GetProductInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{7}
}

func (m *GetProductInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductInfoReq.Unmarshal(m, b)
}
func (m *GetProductInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductInfoReq.Marshal(b, m, deterministic)
}
func (m *GetProductInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductInfoReq.Merge(m, src)
}
func (m *GetProductInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetProductInfoReq.Size(m)
}
func (m *GetProductInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductInfoReq proto.InternalMessageInfo

func (m *GetProductInfoReq) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *GetProductInfoReq) GetPage() *PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetProductInfoResp struct {
	Info                 []*ProductInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	Total                int64          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetProductInfoResp) Reset()         { *m = GetProductInfoResp{} }
func (m *GetProductInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetProductInfoResp) ProtoMessage()    {}
func (*GetProductInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{8}
}

func (m *GetProductInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductInfoResp.Unmarshal(m, b)
}
func (m *GetProductInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductInfoResp.Marshal(b, m, deterministic)
}
func (m *GetProductInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductInfoResp.Merge(m, src)
}
func (m *GetProductInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetProductInfoResp.Size(m)
}
func (m *GetProductInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductInfoResp proto.InternalMessageInfo

func (m *GetProductInfoResp) GetInfo() []*ProductInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetProductInfoResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type DeviceInfo struct {
	ProductID            string                  `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	DeviceName           string                  `protobuf:"bytes,3,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	CreatedTime          int64                   `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	Secret               string                  `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	FirstLogin           int64                   `protobuf:"varint,6,opt,name=firstLogin,proto3" json:"firstLogin,omitempty"`
	LastLogin            int64                   `protobuf:"varint,7,opt,name=lastLogin,proto3" json:"lastLogin,omitempty"`
	Version              *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	LogLevel             int64                   `protobuf:"varint,9,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	Cert                 string                  `protobuf:"bytes,10,opt,name=cert,proto3" json:"cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{9}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *DeviceInfo) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *DeviceInfo) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *DeviceInfo) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *DeviceInfo) GetFirstLogin() int64 {
	if m != nil {
		return m.FirstLogin
	}
	return 0
}

func (m *DeviceInfo) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func (m *DeviceInfo) GetVersion() *wrapperspb.StringValue {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *DeviceInfo) GetLogLevel() int64 {
	if m != nil {
		return m.LogLevel
	}
	return 0
}

func (m *DeviceInfo) GetCert() string {
	if m != nil {
		return m.Cert
	}
	return ""
}

type ManageDeviceReq struct {
	Opt                  int64       `protobuf:"varint,1,opt,name=opt,proto3" json:"opt,omitempty"`
	Info                 *DeviceInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ManageDeviceReq) Reset()         { *m = ManageDeviceReq{} }
func (m *ManageDeviceReq) String() string { return proto.CompactTextString(m) }
func (*ManageDeviceReq) ProtoMessage()    {}
func (*ManageDeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{10}
}

func (m *ManageDeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManageDeviceReq.Unmarshal(m, b)
}
func (m *ManageDeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManageDeviceReq.Marshal(b, m, deterministic)
}
func (m *ManageDeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManageDeviceReq.Merge(m, src)
}
func (m *ManageDeviceReq) XXX_Size() int {
	return xxx_messageInfo_ManageDeviceReq.Size(m)
}
func (m *ManageDeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ManageDeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_ManageDeviceReq proto.InternalMessageInfo

func (m *ManageDeviceReq) GetOpt() int64 {
	if m != nil {
		return m.Opt
	}
	return 0
}

func (m *ManageDeviceReq) GetInfo() *DeviceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetDeviceInfoReq struct {
	DeviceName           string    `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	ProductID            string    `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Page                 *PageInfo `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDeviceInfoReq) Reset()         { *m = GetDeviceInfoReq{} }
func (m *GetDeviceInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetDeviceInfoReq) ProtoMessage()    {}
func (*GetDeviceInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{11}
}

func (m *GetDeviceInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceInfoReq.Unmarshal(m, b)
}
func (m *GetDeviceInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceInfoReq.Marshal(b, m, deterministic)
}
func (m *GetDeviceInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceInfoReq.Merge(m, src)
}
func (m *GetDeviceInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetDeviceInfoReq.Size(m)
}
func (m *GetDeviceInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceInfoReq proto.InternalMessageInfo

func (m *GetDeviceInfoReq) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *GetDeviceInfoReq) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *GetDeviceInfoReq) GetPage() *PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetDeviceInfoResp struct {
	Info                 []*DeviceInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	Total                int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDeviceInfoResp) Reset()         { *m = GetDeviceInfoResp{} }
func (m *GetDeviceInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetDeviceInfoResp) ProtoMessage()    {}
func (*GetDeviceInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{12}
}

func (m *GetDeviceInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceInfoResp.Unmarshal(m, b)
}
func (m *GetDeviceInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceInfoResp.Marshal(b, m, deterministic)
}
func (m *GetDeviceInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceInfoResp.Merge(m, src)
}
func (m *GetDeviceInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetDeviceInfoResp.Size(m)
}
func (m *GetDeviceInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceInfoResp proto.InternalMessageInfo

func (m *GetDeviceInfoResp) GetInfo() []*DeviceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *GetDeviceInfoResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

//获取对应日志信息
type GetDeviceLogReq struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	ProductID            string   `protobuf:"bytes,3,opt,name=productID,proto3" json:"productID,omitempty"`
	DataID               string   `protobuf:"bytes,4,opt,name=dataID,proto3" json:"dataID,omitempty"`
	TimeStart            int64    `protobuf:"varint,5,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd              int64    `protobuf:"varint,6,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	Limit                int64    `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceLogReq) Reset()         { *m = GetDeviceLogReq{} }
func (m *GetDeviceLogReq) String() string { return proto.CompactTextString(m) }
func (*GetDeviceLogReq) ProtoMessage()    {}
func (*GetDeviceLogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{13}
}

func (m *GetDeviceLogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceLogReq.Unmarshal(m, b)
}
func (m *GetDeviceLogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceLogReq.Marshal(b, m, deterministic)
}
func (m *GetDeviceLogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceLogReq.Merge(m, src)
}
func (m *GetDeviceLogReq) XXX_Size() int {
	return xxx_messageInfo_GetDeviceLogReq.Size(m)
}
func (m *GetDeviceLogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceLogReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceLogReq proto.InternalMessageInfo

func (m *GetDeviceLogReq) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *GetDeviceLogReq) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *GetDeviceLogReq) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *GetDeviceLogReq) GetDataID() string {
	if m != nil {
		return m.DataID
	}
	return ""
}

func (m *GetDeviceLogReq) GetTimeStart() int64 {
	if m != nil {
		return m.TimeStart
	}
	return 0
}

func (m *GetDeviceLogReq) GetTimeEnd() int64 {
	if m != nil {
		return m.TimeEnd
	}
	return 0
}

func (m *GetDeviceLogReq) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

//设备的日志数据
type DeviceData struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	DataID               string   `protobuf:"bytes,3,opt,name=dataID,proto3" json:"dataID,omitempty"`
	Payload              string   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceData) Reset()         { *m = DeviceData{} }
func (m *DeviceData) String() string { return proto.CompactTextString(m) }
func (*DeviceData) ProtoMessage()    {}
func (*DeviceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{14}
}

func (m *DeviceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceData.Unmarshal(m, b)
}
func (m *DeviceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceData.Marshal(b, m, deterministic)
}
func (m *DeviceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceData.Merge(m, src)
}
func (m *DeviceData) XXX_Size() int {
	return xxx_messageInfo_DeviceData.Size(m)
}
func (m *DeviceData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceData.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceData proto.InternalMessageInfo

func (m *DeviceData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DeviceData) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *DeviceData) GetDataID() string {
	if m != nil {
		return m.DataID
	}
	return ""
}

func (m *DeviceData) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

//获取对应日志信息
type GetDeviceLogResp struct {
	Total                int64         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*DeviceData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDeviceLogResp) Reset()         { *m = GetDeviceLogResp{} }
func (m *GetDeviceLogResp) String() string { return proto.CompactTextString(m) }
func (*GetDeviceLogResp) ProtoMessage()    {}
func (*GetDeviceLogResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{15}
}

func (m *GetDeviceLogResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceLogResp.Unmarshal(m, b)
}
func (m *GetDeviceLogResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceLogResp.Marshal(b, m, deterministic)
}
func (m *GetDeviceLogResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceLogResp.Merge(m, src)
}
func (m *GetDeviceLogResp) XXX_Size() int {
	return xxx_messageInfo_GetDeviceLogResp.Size(m)
}
func (m *GetDeviceLogResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceLogResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceLogResp proto.InternalMessageInfo

func (m *GetDeviceLogResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetDeviceLogResp) GetData() []*DeviceData {
	if m != nil {
		return m.Data
	}
	return nil
}

//实时获取对应信息
type GetDeviceDataReq struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	ProductID            string   `protobuf:"bytes,3,opt,name=productID,proto3" json:"productID,omitempty"`
	DataID               string   `protobuf:"bytes,4,opt,name=dataID,proto3" json:"dataID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceDataReq) Reset()         { *m = GetDeviceDataReq{} }
func (m *GetDeviceDataReq) String() string { return proto.CompactTextString(m) }
func (*GetDeviceDataReq) ProtoMessage()    {}
func (*GetDeviceDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{16}
}

func (m *GetDeviceDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceDataReq.Unmarshal(m, b)
}
func (m *GetDeviceDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceDataReq.Marshal(b, m, deterministic)
}
func (m *GetDeviceDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceDataReq.Merge(m, src)
}
func (m *GetDeviceDataReq) XXX_Size() int {
	return xxx_messageInfo_GetDeviceDataReq.Size(m)
}
func (m *GetDeviceDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceDataReq proto.InternalMessageInfo

func (m *GetDeviceDataReq) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *GetDeviceDataReq) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *GetDeviceDataReq) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *GetDeviceDataReq) GetDataID() string {
	if m != nil {
		return m.DataID
	}
	return ""
}

//实时获取对应信息
type GetDeviceDataResp struct {
	Data                 []*DeviceData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDeviceDataResp) Reset()         { *m = GetDeviceDataResp{} }
func (m *GetDeviceDataResp) String() string { return proto.CompactTextString(m) }
func (*GetDeviceDataResp) ProtoMessage()    {}
func (*GetDeviceDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{17}
}

func (m *GetDeviceDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceDataResp.Unmarshal(m, b)
}
func (m *GetDeviceDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceDataResp.Marshal(b, m, deterministic)
}
func (m *GetDeviceDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceDataResp.Merge(m, src)
}
func (m *GetDeviceDataResp) XXX_Size() int {
	return xxx_messageInfo_GetDeviceDataResp.Size(m)
}
func (m *GetDeviceDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceDataResp proto.InternalMessageInfo

func (m *GetDeviceDataResp) GetData() []*DeviceData {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendActionReq struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	ActionId             string   `protobuf:"bytes,3,opt,name=actionId,proto3" json:"actionId,omitempty"`
	InputParams          string   `protobuf:"bytes,4,opt,name=inputParams,proto3" json:"inputParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendActionReq) Reset()         { *m = SendActionReq{} }
func (m *SendActionReq) String() string { return proto.CompactTextString(m) }
func (*SendActionReq) ProtoMessage()    {}
func (*SendActionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{18}
}

func (m *SendActionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActionReq.Unmarshal(m, b)
}
func (m *SendActionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActionReq.Marshal(b, m, deterministic)
}
func (m *SendActionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActionReq.Merge(m, src)
}
func (m *SendActionReq) XXX_Size() int {
	return xxx_messageInfo_SendActionReq.Size(m)
}
func (m *SendActionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActionReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendActionReq proto.InternalMessageInfo

func (m *SendActionReq) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *SendActionReq) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *SendActionReq) GetActionId() string {
	if m != nil {
		return m.ActionId
	}
	return ""
}

func (m *SendActionReq) GetInputParams() string {
	if m != nil {
		return m.InputParams
	}
	return ""
}

type SendActionResp struct {
	ClientToken          string   `protobuf:"bytes,1,opt,name=clientToken,proto3" json:"clientToken,omitempty"`
	OutputParams         string   `protobuf:"bytes,2,opt,name=outputParams,proto3" json:"outputParams,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Code                 int64    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendActionResp) Reset()         { *m = SendActionResp{} }
func (m *SendActionResp) String() string { return proto.CompactTextString(m) }
func (*SendActionResp) ProtoMessage()    {}
func (*SendActionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{19}
}

func (m *SendActionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActionResp.Unmarshal(m, b)
}
func (m *SendActionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActionResp.Marshal(b, m, deterministic)
}
func (m *SendActionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActionResp.Merge(m, src)
}
func (m *SendActionResp) XXX_Size() int {
	return xxx_messageInfo_SendActionResp.Size(m)
}
func (m *SendActionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActionResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendActionResp proto.InternalMessageInfo

func (m *SendActionResp) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

func (m *SendActionResp) GetOutputParams() string {
	if m != nil {
		return m.OutputParams
	}
	return ""
}

func (m *SendActionResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SendActionResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type SendPropertyReq struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=productID,proto3" json:"productID,omitempty"`
	DeviceName           string   `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DataTimestamp        int64    `protobuf:"varint,4,opt,name=dataTimestamp,proto3" json:"dataTimestamp,omitempty"`
	Method               string   `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPropertyReq) Reset()         { *m = SendPropertyReq{} }
func (m *SendPropertyReq) String() string { return proto.CompactTextString(m) }
func (*SendPropertyReq) ProtoMessage()    {}
func (*SendPropertyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{20}
}

func (m *SendPropertyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPropertyReq.Unmarshal(m, b)
}
func (m *SendPropertyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPropertyReq.Marshal(b, m, deterministic)
}
func (m *SendPropertyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPropertyReq.Merge(m, src)
}
func (m *SendPropertyReq) XXX_Size() int {
	return xxx_messageInfo_SendPropertyReq.Size(m)
}
func (m *SendPropertyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPropertyReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendPropertyReq proto.InternalMessageInfo

func (m *SendPropertyReq) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *SendPropertyReq) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *SendPropertyReq) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SendPropertyReq) GetDataTimestamp() int64 {
	if m != nil {
		return m.DataTimestamp
	}
	return 0
}

func (m *SendPropertyReq) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type SendPropertyResp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ClientToken          string   `protobuf:"bytes,3,opt,name=clientToken,proto3" json:"clientToken,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPropertyResp) Reset()         { *m = SendPropertyResp{} }
func (m *SendPropertyResp) String() string { return proto.CompactTextString(m) }
func (*SendPropertyResp) ProtoMessage()    {}
func (*SendPropertyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5a2dc3ea2af5e6, []int{21}
}

func (m *SendPropertyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPropertyResp.Unmarshal(m, b)
}
func (m *SendPropertyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPropertyResp.Marshal(b, m, deterministic)
}
func (m *SendPropertyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPropertyResp.Merge(m, src)
}
func (m *SendPropertyResp) XXX_Size() int {
	return xxx_messageInfo_SendPropertyResp.Size(m)
}
func (m *SendPropertyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPropertyResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendPropertyResp proto.InternalMessageInfo

func (m *SendPropertyResp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SendPropertyResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *SendPropertyResp) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

func (m *SendPropertyResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*PageInfo)(nil), "dm.PageInfo")
	proto.RegisterType((*Response)(nil), "dm.Response")
	proto.RegisterType((*ManResp)(nil), "dm.ManResp")
	proto.RegisterType((*LoginAuthReq)(nil), "dm.LoginAuthReq")
	proto.RegisterType((*AccessAuthReq)(nil), "dm.AccessAuthReq")
	proto.RegisterType((*ProductInfo)(nil), "dm.ProductInfo")
	proto.RegisterType((*ManageProductReq)(nil), "dm.ManageProductReq")
	proto.RegisterType((*GetProductInfoReq)(nil), "dm.GetProductInfoReq")
	proto.RegisterType((*GetProductInfoResp)(nil), "dm.GetProductInfoResp")
	proto.RegisterType((*DeviceInfo)(nil), "dm.DeviceInfo")
	proto.RegisterType((*ManageDeviceReq)(nil), "dm.ManageDeviceReq")
	proto.RegisterType((*GetDeviceInfoReq)(nil), "dm.GetDeviceInfoReq")
	proto.RegisterType((*GetDeviceInfoResp)(nil), "dm.GetDeviceInfoResp")
	proto.RegisterType((*GetDeviceLogReq)(nil), "dm.GetDeviceLogReq")
	proto.RegisterType((*DeviceData)(nil), "dm.DeviceData")
	proto.RegisterType((*GetDeviceLogResp)(nil), "dm.GetDeviceLogResp")
	proto.RegisterType((*GetDeviceDataReq)(nil), "dm.GetDeviceDataReq")
	proto.RegisterType((*GetDeviceDataResp)(nil), "dm.GetDeviceDataResp")
	proto.RegisterType((*SendActionReq)(nil), "dm.SendActionReq")
	proto.RegisterType((*SendActionResp)(nil), "dm.SendActionResp")
	proto.RegisterType((*SendPropertyReq)(nil), "dm.SendPropertyReq")
	proto.RegisterType((*SendPropertyResp)(nil), "dm.SendPropertyResp")
}

func init() { proto.RegisterFile("dm.proto", fileDescriptor_2a5a2dc3ea2af5e6) }

var fileDescriptor_2a5a2dc3ea2af5e6 = []byte{
	// 1184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6a, 0xe4, 0x46,
	0x10, 0x46, 0xd2, 0xd8, 0x9e, 0xa9, 0x99, 0xb1, 0xbd, 0x1d, 0xaf, 0x51, 0x86, 0xc5, 0x18, 0x25,
	0x07, 0x43, 0xc8, 0x2c, 0xd8, 0xb0, 0x49, 0x96, 0x90, 0x60, 0x98, 0x60, 0x06, 0xec, 0xc4, 0x68,
	0x4c, 0xee, 0xbd, 0x52, 0x8f, 0x2c, 0x22, 0xa9, 0xdb, 0xea, 0x1e, 0x2f, 0xce, 0x29, 0x04, 0x72,
	0xca, 0x35, 0x2f, 0x90, 0x6b, 0xee, 0x79, 0x8c, 0x3c, 0x4e, 0xee, 0xa1, 0x7f, 0x24, 0xb5, 0x34,
	0xfe, 0x83, 0xc0, 0x9e, 0xa4, 0xfa, 0xfa, 0xef, 0xab, 0xaa, 0xaf, 0xab, 0x0b, 0xfa, 0x71, 0x3e,
	0x65, 0x25, 0x15, 0x14, 0xb9, 0x71, 0x3e, 0x39, 0x48, 0x28, 0x4d, 0x32, 0xf2, 0x5a, 0x21, 0xef,
	0x56, 0xcb, 0xd7, 0xef, 0x4b, 0xcc, 0x18, 0x29, 0xb9, 0x9e, 0x13, 0xbc, 0x85, 0xfe, 0x25, 0x4e,
	0xc8, 0xbc, 0x58, 0x52, 0x84, 0xa0, 0xc7, 0x70, 0x42, 0x7c, 0xe7, 0xd0, 0x39, 0xf2, 0x42, 0xf5,
	0x8f, 0x26, 0xd0, 0x97, 0xdf, 0x45, 0xfa, 0x33, 0xf1, 0x5d, 0x85, 0xd7, 0x76, 0x00, 0xd0, 0x0f,
	0x09, 0x67, 0xb4, 0xe0, 0x24, 0xf8, 0x18, 0xb6, 0x2e, 0x70, 0x21, 0x4d, 0xb4, 0x0d, 0xee, 0x7c,
	0x66, 0x36, 0x71, 0xe7, 0xb3, 0xe0, 0x0f, 0x07, 0x46, 0xe7, 0x34, 0x49, 0x8b, 0xd3, 0x95, 0xb8,
	0x0e, 0xc9, 0x8d, 0xdc, 0x73, 0xc5, 0x49, 0x59, 0xe0, 0x5c, 0x9f, 0x35, 0x08, 0x6b, 0x5b, 0x9f,
	0xc7, 0xf9, 0x7b, 0x5a, 0xc6, 0xea, 0xbc, 0x41, 0x58, 0xdb, 0x72, 0x2c, 0xca, 0x52, 0x52, 0x88,
	0xf9, 0xcc, 0xf7, 0xf4, 0x58, 0x65, 0xcb, 0x43, 0x53, 0xe6, 0xf7, 0x14, 0xea, 0xa6, 0x0c, 0x1d,
	0xc2, 0x30, 0x22, 0xa5, 0x48, 0x97, 0x69, 0x84, 0x05, 0xf1, 0x37, 0x0e, 0x9d, 0xa3, 0x51, 0x68,
	0x43, 0xc1, 0x6f, 0x0e, 0x8c, 0x4f, 0xa3, 0x88, 0x70, 0xfe, 0x1c, 0x5e, 0x7b, 0xb0, 0x21, 0x28,
	0x4b, 0x23, 0x43, 0x4a, 0x1b, 0x8f, 0x32, 0xda, 0x87, 0x4d, 0xac, 0xb6, 0x37, 0xac, 0x8c, 0x65,
	0x98, 0x6e, 0x54, 0x4c, 0x83, 0x7f, 0x3d, 0x18, 0x5e, 0x96, 0x34, 0x5e, 0x45, 0x42, 0x65, 0x41,
	0x32, 0x2f, 0x09, 0x16, 0x24, 0xbe, 0x4a, 0xf3, 0x2a, 0x19, 0x36, 0x84, 0x5e, 0xc1, 0x80, 0x99,
	0x05, 0x33, 0xc3, 0xa7, 0x01, 0xe4, 0x7a, 0x63, 0x7c, 0x2f, 0x1d, 0xd1, 0xb4, 0x6c, 0x48, 0xb2,
	0xc6, 0x2b, 0x71, 0x7d, 0x41, 0x63, 0xa2, 0xb8, 0x79, 0x61, 0x6d, 0xa3, 0x03, 0x80, 0x98, 0xdc,
	0xa6, 0x11, 0xb9, 0xba, 0x63, 0x3a, 0x6c, 0x5e, 0x68, 0x21, 0x72, 0x5c, 0x46, 0x2f, 0xa1, 0xe5,
	0xdd, 0x7c, 0xe6, 0x6f, 0xea, 0xf1, 0x06, 0x41, 0x3e, 0x6c, 0x15, 0x44, 0xa8, 0xc5, 0x5b, 0x6a,
	0xb0, 0x32, 0x25, 0xeb, 0x18, 0x0b, 0x7c, 0x29, 0x65, 0xe7, 0xf7, 0xd5, 0x58, 0x03, 0xa0, 0x00,
	0x46, 0x78, 0x25, 0x68, 0x48, 0x92, 0x94, 0x0b, 0x52, 0xfa, 0x03, 0x35, 0xa1, 0x85, 0xc9, 0x88,
	0x72, 0x12, 0x95, 0x44, 0xf8, 0xa0, 0x23, 0xaa, 0x2d, 0xf4, 0x25, 0xf4, 0x05, 0xc9, 0x59, 0x26,
	0x13, 0x3d, 0x3c, 0x74, 0x8e, 0x86, 0xc7, 0xaf, 0xa6, 0x5a, 0xf6, 0xd3, 0x4a, 0xf6, 0xd3, 0x85,
	0x28, 0xd3, 0x22, 0xf9, 0x11, 0x67, 0x2b, 0x12, 0xd6, 0xb3, 0xd1, 0x37, 0x30, 0x8c, 0x09, 0x8f,
	0xca, 0x94, 0x89, 0x94, 0x16, 0xfe, 0xe8, 0x19, 0x8b, 0xed, 0x05, 0xe8, 0x2d, 0x0c, 0x62, 0x72,
	0xbb, 0x10, 0x58, 0xac, 0xb8, 0x3f, 0x7e, 0xc6, 0xea, 0x66, 0x7a, 0x30, 0x87, 0xdd, 0x0b, 0x5c,
	0xe0, 0x84, 0x98, 0xe4, 0x4b, 0x05, 0xee, 0x82, 0x47, 0x99, 0x30, 0x39, 0x97, 0xbf, 0xe8, 0x13,
	0xe8, 0xa5, 0xc5, 0x92, 0xaa, 0x34, 0x0f, 0x8f, 0x77, 0xa6, 0x71, 0x3e, 0xb5, 0xc4, 0x12, 0xaa,
	0xc1, 0x60, 0x01, 0x2f, 0xce, 0x88, 0xb0, 0x71, 0x72, 0xd3, 0x56, 0x89, 0xb3, 0xae, 0x12, 0x7d,
	0xd7, 0xf5, 0xbe, 0x23, 0xb5, 0xaf, 0xa9, 0x03, 0xfa, 0xe6, 0x07, 0x3f, 0x00, 0xea, 0x6e, 0xca,
	0x59, 0xcd, 0xc7, 0x39, 0xf4, 0x1e, 0xe4, 0xa3, 0x2f, 0x8b, 0xc0, 0x99, 0xa9, 0x18, 0xda, 0x08,
	0xfe, 0x72, 0x01, 0x66, 0x4a, 0x49, 0x4a, 0xe7, 0x8f, 0xf3, 0xab, 0x75, 0x68, 0x89, 0xd8, 0x42,
	0xba, 0xb7, 0xa4, 0xb7, 0x7e, 0x4b, 0x1a, 0xb5, 0x6c, 0xb4, 0xd4, 0x72, 0x00, 0xb0, 0x4c, 0x4b,
	0x2e, 0x54, 0x49, 0xaa, 0x14, 0xdc, 0x20, 0x92, 0x57, 0x86, 0xab, 0x61, 0xad, 0xe1, 0x06, 0x40,
	0x6f, 0x60, 0xeb, 0x96, 0x94, 0x5c, 0xaa, 0xa5, 0xff, 0x8c, 0x7c, 0x57, 0x93, 0xe5, 0x9d, 0xcb,
	0x68, 0x72, 0x4e, 0x6e, 0x49, 0x66, 0xb4, 0x5d, 0xdb, 0xb2, 0xee, 0xca, 0xc2, 0x64, 0x54, 0xad,
	0xfe, 0x83, 0x33, 0xd8, 0xd1, 0xea, 0xd0, 0x11, 0xbb, 0x5f, 0x1c, 0x41, 0x4b, 0x1c, 0xdb, 0x32,
	0x19, 0x4d, 0x80, 0x8d, 0x36, 0x4a, 0xd8, 0x3d, 0x23, 0xc2, 0x82, 0xc9, 0x4d, 0x27, 0xb8, 0xce,
	0x5a, 0x70, 0x9f, 0x2a, 0x30, 0x5a, 0x3a, 0xde, 0x83, 0xd2, 0xb9, 0x50, 0x7a, 0xb4, 0xcf, 0xe4,
	0xac, 0x26, 0xab, 0x95, 0x73, 0x2f, 0xd9, 0x07, 0x84, 0xf3, 0x8f, 0x03, 0x3b, 0xf5, 0x7e, 0xe7,
	0x34, 0x91, 0x2e, 0xec, 0xc3, 0x66, 0x4e, 0xc4, 0x35, 0x8d, 0x0d, 0x7d, 0x63, 0x75, 0x5c, 0x73,
	0x1f, 0x77, 0xcd, 0xeb, 0xba, 0xb6, 0x0f, 0x9b, 0xb2, 0x24, 0xcd, 0x67, 0x55, 0xcd, 0xd6, 0x96,
	0x5c, 0x25, 0xd2, 0x9c, 0x2c, 0x04, 0x2e, 0x85, 0x29, 0x8a, 0x0d, 0x20, 0x6b, 0x9e, 0x34, 0xbe,
	0x2b, 0x62, 0x23, 0xa7, 0xca, 0x94, 0xfe, 0x64, 0x69, 0x9e, 0x0a, 0xa3, 0x23, 0x6d, 0x04, 0xa2,
	0xba, 0x07, 0x33, 0x2c, 0x70, 0xb5, 0x37, 0x17, 0x38, 0x67, 0x26, 0xb9, 0x0d, 0x60, 0xf9, 0xe9,
	0xb6, 0xfc, 0x6c, 0x98, 0x7a, 0x2d, 0xa6, 0x3e, 0x6c, 0x31, 0x7c, 0x97, 0x51, 0x1c, 0x1b, 0x17,
	0x2a, 0x33, 0x38, 0xb7, 0x84, 0xa0, 0x82, 0xc8, 0x59, 0x13, 0x6f, 0xc7, 0x8a, 0xb7, 0xcc, 0x94,
	0xdc, 0xcd, 0x77, 0xbb, 0x99, 0x92, 0x7c, 0x43, 0x35, 0x16, 0xfc, 0xe2, 0x58, 0xdb, 0x29, 0xfc,
	0x43, 0x27, 0x25, 0xf8, 0xc2, 0x52, 0x99, 0x66, 0xa0, 0x55, 0xa6, 0xb8, 0x3b, 0x8f, 0x70, 0xff,
	0xdd, 0x81, 0xf1, 0x82, 0x14, 0xf1, 0x69, 0x24, 0x8b, 0xf8, 0xd3, 0xb5, 0xf2, 0x29, 0xfa, 0xf2,
	0x3d, 0x55, 0x5b, 0xcd, 0xe3, 0xaa, 0x0b, 0xa8, 0x6c, 0x59, 0xa7, 0xd2, 0x82, 0xad, 0xc4, 0x25,
	0x2e, 0x71, 0x5e, 0xb5, 0x02, 0x36, 0x14, 0xfc, 0xea, 0xc0, 0xb6, 0xcd, 0x86, 0xeb, 0xe6, 0x45,
	0xb5, 0x11, 0x57, 0xf4, 0x27, 0x52, 0x18, 0x42, 0x36, 0x24, 0x9f, 0x4b, 0xba, 0x12, 0xcd, 0xbe,
	0x9a, 0x54, 0x0b, 0x53, 0x05, 0x50, 0xbf, 0x4c, 0x46, 0x22, 0xda, 0x52, 0xe5, 0xa6, 0x79, 0xfa,
	0xd5, 0x7f, 0xf0, 0xa7, 0x03, 0x3b, 0x92, 0xc4, 0x65, 0x49, 0x19, 0x29, 0xc5, 0xdd, 0xff, 0x0f,
	0x0a, 0x32, 0x89, 0xd0, 0x67, 0xab, 0x7f, 0xf4, 0x29, 0x8c, 0xe5, 0xf7, 0xaa, 0x96, 0xbb, 0xa6,
	0xd0, 0x06, 0x2d, 0x15, 0x6d, 0xd8, 0x2a, 0x0a, 0x04, 0xec, 0xb6, 0x29, 0x72, 0x56, 0xfb, 0xe2,
	0x34, 0xbe, 0x58, 0x7e, 0xbb, 0x2d, 0xbf, 0x3b, 0x51, 0xf5, 0xd6, 0xa3, 0x5a, 0x71, 0xee, 0x35,
	0x9c, 0x8f, 0xff, 0xee, 0x81, 0x3b, 0xcb, 0xd1, 0x67, 0x30, 0xc8, 0xaa, 0x1e, 0x16, 0xed, 0x4a,
	0x59, 0xd9, 0x2d, 0xed, 0x44, 0x55, 0xc1, 0xaa, 0x19, 0x46, 0x9f, 0x03, 0xe0, 0xba, 0xb3, 0x44,
	0x2f, 0xe4, 0x58, 0xab, 0xd3, 0xec, 0x4c, 0x3f, 0x81, 0x51, 0x6e, 0xd5, 0x7a, 0xf4, 0x91, 0x1c,
	0xed, 0x54, 0xff, 0x49, 0xa7, 0x60, 0xa2, 0x37, 0x30, 0xce, 0xed, 0xf6, 0x01, 0xed, 0x35, 0xab,
	0x9a, 0x8e, 0x62, 0xd2, 0x7d, 0xa1, 0xd1, 0xb7, 0xb0, 0x9d, 0xb4, 0x9e, 0x75, 0xf4, 0x52, 0x4e,
	0x59, 0xeb, 0x1f, 0x26, 0xfb, 0xf7, 0xc1, 0x9c, 0xa1, 0xaf, 0x61, 0x9c, 0xd8, 0xc5, 0x5d, 0x1f,
	0xdc, 0x7d, 0x63, 0x26, 0x2f, 0xef, 0x41, 0x3b, 0xab, 0x55, 0xf9, 0x6b, 0xaf, 0x36, 0x95, 0xa4,
	0xb3, 0xba, 0xbe, 0xdd, 0x5f, 0xc1, 0x28, 0xb1, 0x6a, 0x98, 0x8e, 0x54, 0xe7, 0x69, 0x98, 0xec,
	0xad, 0x83, 0x9c, 0xa1, 0x13, 0x80, 0xe6, 0x96, 0xe9, 0x9c, 0xb4, 0x6a, 0xc0, 0x04, 0x75, 0x21,
	0x7d, 0x9e, 0x2d, 0x39, 0x7d, 0x5e, 0xe7, 0x9e, 0xe8, 0xf3, 0xba, 0xca, 0x7c, 0xb7, 0xa9, 0xfa,
	0x81, 0x93, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x32, 0xf9, 0xdd, 0xdd, 0x8f, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DmClient is the client API for Dm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DmClient interface {
	//登录认证
	LoginAuth(ctx context.Context, in *LoginAuthReq, opts ...grpc.CallOption) (*Response, error)
	//操作认证
	AccessAuth(ctx context.Context, in *AccessAuthReq, opts ...grpc.CallOption) (*Response, error)
	//设备管理
	ManageDevice(ctx context.Context, in *ManageDeviceReq, opts ...grpc.CallOption) (*DeviceInfo, error)
	//产品管理
	ManageProduct(ctx context.Context, in *ManageProductReq, opts ...grpc.CallOption) (*ProductInfo, error)
	//获取产品信息
	GetProductInfo(ctx context.Context, in *GetProductInfoReq, opts ...grpc.CallOption) (*GetProductInfoResp, error)
	//获取设备信息
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoReq, opts ...grpc.CallOption) (*GetDeviceInfoResp, error)
	//获取设备最新数据
	GetDeviceData(ctx context.Context, in *GetDeviceDataReq, opts ...grpc.CallOption) (*GetDeviceDataResp, error)
	//获取设备日志信息
	GetDeviceLog(ctx context.Context, in *GetDeviceLogReq, opts ...grpc.CallOption) (*GetDeviceLogResp, error)
	//同步调用设备行为
	SendAction(ctx context.Context, in *SendActionReq, opts ...grpc.CallOption) (*SendActionResp, error)
	//同步调用设备属性
	SendProperty(ctx context.Context, in *SendPropertyReq, opts ...grpc.CallOption) (*SendPropertyResp, error)
}

type dmClient struct {
	cc *grpc.ClientConn
}

func NewDmClient(cc *grpc.ClientConn) DmClient {
	return &dmClient{cc}
}

func (c *dmClient) LoginAuth(ctx context.Context, in *LoginAuthReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dm.Dm/loginAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) AccessAuth(ctx context.Context, in *AccessAuthReq, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/dm.Dm/accessAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) ManageDevice(ctx context.Context, in *ManageDeviceReq, opts ...grpc.CallOption) (*DeviceInfo, error) {
	out := new(DeviceInfo)
	err := c.cc.Invoke(ctx, "/dm.Dm/manageDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) ManageProduct(ctx context.Context, in *ManageProductReq, opts ...grpc.CallOption) (*ProductInfo, error) {
	out := new(ProductInfo)
	err := c.cc.Invoke(ctx, "/dm.Dm/manageProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) GetProductInfo(ctx context.Context, in *GetProductInfoReq, opts ...grpc.CallOption) (*GetProductInfoResp, error) {
	out := new(GetProductInfoResp)
	err := c.cc.Invoke(ctx, "/dm.Dm/getProductInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoReq, opts ...grpc.CallOption) (*GetDeviceInfoResp, error) {
	out := new(GetDeviceInfoResp)
	err := c.cc.Invoke(ctx, "/dm.Dm/getDeviceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) GetDeviceData(ctx context.Context, in *GetDeviceDataReq, opts ...grpc.CallOption) (*GetDeviceDataResp, error) {
	out := new(GetDeviceDataResp)
	err := c.cc.Invoke(ctx, "/dm.Dm/getDeviceData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) GetDeviceLog(ctx context.Context, in *GetDeviceLogReq, opts ...grpc.CallOption) (*GetDeviceLogResp, error) {
	out := new(GetDeviceLogResp)
	err := c.cc.Invoke(ctx, "/dm.Dm/getDeviceLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) SendAction(ctx context.Context, in *SendActionReq, opts ...grpc.CallOption) (*SendActionResp, error) {
	out := new(SendActionResp)
	err := c.cc.Invoke(ctx, "/dm.Dm/SendAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dmClient) SendProperty(ctx context.Context, in *SendPropertyReq, opts ...grpc.CallOption) (*SendPropertyResp, error) {
	out := new(SendPropertyResp)
	err := c.cc.Invoke(ctx, "/dm.Dm/SendProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DmServer is the server API for Dm service.
type DmServer interface {
	//登录认证
	LoginAuth(context.Context, *LoginAuthReq) (*Response, error)
	//操作认证
	AccessAuth(context.Context, *AccessAuthReq) (*Response, error)
	//设备管理
	ManageDevice(context.Context, *ManageDeviceReq) (*DeviceInfo, error)
	//产品管理
	ManageProduct(context.Context, *ManageProductReq) (*ProductInfo, error)
	//获取产品信息
	GetProductInfo(context.Context, *GetProductInfoReq) (*GetProductInfoResp, error)
	//获取设备信息
	GetDeviceInfo(context.Context, *GetDeviceInfoReq) (*GetDeviceInfoResp, error)
	//获取设备最新数据
	GetDeviceData(context.Context, *GetDeviceDataReq) (*GetDeviceDataResp, error)
	//获取设备日志信息
	GetDeviceLog(context.Context, *GetDeviceLogReq) (*GetDeviceLogResp, error)
	//同步调用设备行为
	SendAction(context.Context, *SendActionReq) (*SendActionResp, error)
	//同步调用设备属性
	SendProperty(context.Context, *SendPropertyReq) (*SendPropertyResp, error)
}

// UnimplementedDmServer can be embedded to have forward compatible implementations.
type UnimplementedDmServer struct {
}

func (*UnimplementedDmServer) LoginAuth(ctx context.Context, req *LoginAuthReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAuth not implemented")
}
func (*UnimplementedDmServer) AccessAuth(ctx context.Context, req *AccessAuthReq) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccessAuth not implemented")
}
func (*UnimplementedDmServer) ManageDevice(ctx context.Context, req *ManageDeviceReq) (*DeviceInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManageDevice not implemented")
}
func (*UnimplementedDmServer) ManageProduct(ctx context.Context, req *ManageProductReq) (*ProductInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManageProduct not implemented")
}
func (*UnimplementedDmServer) GetProductInfo(ctx context.Context, req *GetProductInfoReq) (*GetProductInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductInfo not implemented")
}
func (*UnimplementedDmServer) GetDeviceInfo(ctx context.Context, req *GetDeviceInfoReq) (*GetDeviceInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (*UnimplementedDmServer) GetDeviceData(ctx context.Context, req *GetDeviceDataReq) (*GetDeviceDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceData not implemented")
}
func (*UnimplementedDmServer) GetDeviceLog(ctx context.Context, req *GetDeviceLogReq) (*GetDeviceLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceLog not implemented")
}
func (*UnimplementedDmServer) SendAction(ctx context.Context, req *SendActionReq) (*SendActionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAction not implemented")
}
func (*UnimplementedDmServer) SendProperty(ctx context.Context, req *SendPropertyReq) (*SendPropertyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendProperty not implemented")
}

func RegisterDmServer(s *grpc.Server, srv DmServer) {
	s.RegisterService(&_Dm_serviceDesc, srv)
}

func _Dm_LoginAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).LoginAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/LoginAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).LoginAuth(ctx, req.(*LoginAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_AccessAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).AccessAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/AccessAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).AccessAuth(ctx, req.(*AccessAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_ManageDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).ManageDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/ManageDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).ManageDevice(ctx, req.(*ManageDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_ManageProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageProductReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).ManageProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/ManageProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).ManageProduct(ctx, req.(*ManageProductReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_GetProductInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).GetProductInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/GetProductInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).GetProductInfo(ctx, req.(*GetProductInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/GetDeviceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_GetDeviceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).GetDeviceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/GetDeviceData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).GetDeviceData(ctx, req.(*GetDeviceDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_GetDeviceLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).GetDeviceLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/GetDeviceLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).GetDeviceLog(ctx, req.(*GetDeviceLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_SendAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendActionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).SendAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/SendAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).SendAction(ctx, req.(*SendActionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dm_SendProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPropertyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmServer).SendProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dm.Dm/SendProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmServer).SendProperty(ctx, req.(*SendPropertyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dm.Dm",
	HandlerType: (*DmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "loginAuth",
			Handler:    _Dm_LoginAuth_Handler,
		},
		{
			MethodName: "accessAuth",
			Handler:    _Dm_AccessAuth_Handler,
		},
		{
			MethodName: "manageDevice",
			Handler:    _Dm_ManageDevice_Handler,
		},
		{
			MethodName: "manageProduct",
			Handler:    _Dm_ManageProduct_Handler,
		},
		{
			MethodName: "getProductInfo",
			Handler:    _Dm_GetProductInfo_Handler,
		},
		{
			MethodName: "getDeviceInfo",
			Handler:    _Dm_GetDeviceInfo_Handler,
		},
		{
			MethodName: "getDeviceData",
			Handler:    _Dm_GetDeviceData_Handler,
		},
		{
			MethodName: "getDeviceLog",
			Handler:    _Dm_GetDeviceLog_Handler,
		},
		{
			MethodName: "SendAction",
			Handler:    _Dm_SendAction_Handler,
		},
		{
			MethodName: "SendProperty",
			Handler:    _Dm_SendProperty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dm.proto",
}
