// Code generated by goctl. DO NOT EDIT!
// Source: dd.proto

package server

import (
	"context"

	"github.com/i-Things/things/src/ddsvr/internal/logic"
	"github.com/i-Things/things/src/ddsvr/internal/svc"
	"github.com/i-Things/things/src/ddsvr/pb/dd"
)

type DdServer struct {
	svcCtx *svc.ServiceContext
	dd.UnimplementedDdServer
}

func NewDdServer(svcCtx *svc.ServiceContext) *DdServer {
	return &DdServer{
		svcCtx: svcCtx,
	}
}

// ping pong 测试
func (s *DdServer) Ping(ctx context.Context, in *dd.Empty) (*dd.Empty, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
