#设备管理模块配置-dmsvr
Name: dm.rpc
ListenOn: 0.0.0.0:9081
CpuThreshold: 0
Timeout: 1000000
Log:
  Encoding: plain
Etcd:
  Hosts:
    - etcd:2379
  Key: dm.rpc
  #Mode: file
CacheRedis:
  - Host: redis:6379
    Pass:
    Type: node
Database:
  DBType: mysql
  DSN: root:password@tcp(mysql:3306)/iThings?charset=utf8mb4&collation=utf8mb4_bin&parseTime=true&loc=Asia%2FShanghai

TSDB:
  Driver: taosRestful
  DSN: root:taosdata@http(tdengine:6041)/ithings?readBufferSize=52428800
#  DSN: root:taosdata@ws(tdengine:6041)/ithings?readBufferSize=52428800
#  Driver: taosSql
#  DSN: root:taosdata@tcp(localhost:6030)/ithings
AuthWhite:
  Users:
    - UserName: dgsvr
      Password: iThings
    - UserName: pwumeisvr
      Password: iThings
    - UserName: paliMqttsvr
      Password: iThings
  IpRange:
    - 127.0.0.1
    - 172.18.0.1
    - 172.20.0.1
    - 192.168.1.1
    - 172.20.0.0/16

OssConf:
  OssType: minio
  PublicBucketName: ithings-public
  PrivateBucketName: ithings-private
  TemporaryBucketName: ithings-temporary
  AccessKeyID: root
  AccessKeySecret: password
  Location: minio:9000
  ConnectTimeout: 6000
  ReadWriteTimeout: 60000
  UseSSL: false

DgRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
DmRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000
UdRpc:
  Enable: true
  Mode: direct
  Conf:
    Timeout: 1000000

TimedJobRpc:
  Enable: true
  Mode: grpc
  Conf:
    Timeout: 1000000
    Etcd:
      Hosts:
        - etcd:2379
      Key: timedjob.rpc

SysRpc:
  Enable: true
  Mode: grpc
  Conf:
    Timeout: 1000000
    Etcd:
      Hosts:
        - etcd:2379
      Key: sys.rpc

Event:
  Nats:
    Url: nats://nats:4222