#设备管理模块配置-dmsvr
Name: dm.rpc
ListenOn: 0.0.0.0:9081
CpuThreshold: 0
Timeout: 1000000
Log:
  Encoding: plain
Etcd:
  Hosts:
    - etcd:2379
  Key: dm.rpc
  #Mode: file
CacheRedis:
  - Host: redis:6379
    Pass:
    Type: node
TSDB:
  Driver: taosRestful
  DSN: root:taosdata@http(tdengine:6041)/ithings?readBufferSize=52428800
#  DSN: root:taosdata@ws(tdengine:6041)/ithings?readBufferSize=52428800
#  Driver: taosSql
#  DSN: root:taosdata@tcp(localhost:6030)/ithings
AuthWhite:
  Users:
    - UserName: dgsvr
      Password: iThings
    - UserName: pwumeisvr
      Password: iThings
    - UserName: paliMqttsvr
      Password: iThings
OssConf:
  OssType: minio
  PublicBucketName: ithings-public
  PrivateBucketName: ithings-private
  TemporaryBucketName: ithings-temporary
  AccessKeyID: root
  AccessKeySecret: password
  Location: minio:9000
  ConnectTimeout: 6000
  ReadWriteTimeout: 60000
  UseSSL: false

TimedJobRpc:
  Enable: true
  Mode: grpc
  Conf:
    Timeout: 1000000
    Etcd:
      Hosts:
        - etcd:2379
      Key: timedjob.rpc

SysRpc:
  Enable: true
  Mode: grpc
  Conf:
    Timeout: 1000000
    Etcd:
      Hosts:
        - etcd:2379
      Key: sys.rpc