// Code generated by goctl. DO NOT EDIT.
// Source: timedscheduler.proto

package server

import (
	"context"

	"github.com/i-Things/things/src/timedschedulersvr/internal/logic/timedscheduler"
	"github.com/i-Things/things/src/timedschedulersvr/internal/svc"
	"github.com/i-Things/things/src/timedschedulersvr/pb/timedscheduler"
)

type TimedschedulerServer struct {
	svcCtx *svc.ServiceContext
	timedscheduler.UnimplementedTimedschedulerServer
}

func NewTimedschedulerServer(svcCtx *svc.ServiceContext) *TimedschedulerServer {
	return &TimedschedulerServer{
		svcCtx: svcCtx,
	}
}

// 新增任务
func (s *TimedschedulerServer) JobInfoCreate(ctx context.Context, in *timedscheduler.JobInfo) (*timedscheduler.Response, error) {
	l := timedschedulerlogic.NewJobInfoCreateLogic(ctx, s.svcCtx)
	return l.JobInfoCreate(in)
}

// 更新任务
func (s *TimedschedulerServer) JobInfoUpdate(ctx context.Context, in *timedscheduler.JobInfo) (*timedscheduler.Response, error) {
	l := timedschedulerlogic.NewJobInfoUpdateLogic(ctx, s.svcCtx)
	return l.JobInfoUpdate(in)
}

// 删除任务
func (s *TimedschedulerServer) JobInfoDelete(ctx context.Context, in *timedscheduler.JobInfoDeleteReq) (*timedscheduler.Response, error) {
	l := timedschedulerlogic.NewJobInfoDeleteLogic(ctx, s.svcCtx)
	return l.JobInfoDelete(in)
}

// 获取任务信息列表
func (s *TimedschedulerServer) JobInfoIndex(ctx context.Context, in *timedscheduler.JobInfoIndexReq) (*timedscheduler.JobInfoIndexResp, error) {
	l := timedschedulerlogic.NewJobInfoIndexLogic(ctx, s.svcCtx)
	return l.JobInfoIndex(in)
}

// 获取任务信息详情
func (s *TimedschedulerServer) JobInfoRead(ctx context.Context, in *timedscheduler.JobInfoReadReq) (*timedscheduler.JobInfo, error) {
	l := timedschedulerlogic.NewJobInfoReadLogic(ctx, s.svcCtx)
	return l.JobInfoRead(in)
}
