// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"github.com/i-Things/things/src/syssvr/internal/logic/datamanage"
	"github.com/i-Things/things/src/syssvr/internal/svc"
	"github.com/i-Things/things/src/syssvr/pb/sys"
)

type DataManageServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedDataManageServer
}

func NewDataManageServer(svcCtx *svc.ServiceContext) *DataManageServer {
	return &DataManageServer{
		svcCtx: svcCtx,
	}
}

func (s *DataManageServer) DataProjectMultiUpdate(ctx context.Context, in *sys.DataProjectMultiUpdateReq) (*sys.Response, error) {
	l := datamanagelogic.NewDataProjectMultiUpdateLogic(ctx, s.svcCtx)
	return l.DataProjectMultiUpdate(in)
}

func (s *DataManageServer) DataProjectIndex(ctx context.Context, in *sys.DataProjectIndexReq) (*sys.DataProjectIndexResp, error) {
	l := datamanagelogic.NewDataProjectIndexLogic(ctx, s.svcCtx)
	return l.DataProjectIndex(in)
}

func (s *DataManageServer) DataAreaMultiUpdate(ctx context.Context, in *sys.DataAreaMultiUpdateReq) (*sys.Response, error) {
	l := datamanagelogic.NewDataAreaMultiUpdateLogic(ctx, s.svcCtx)
	return l.DataAreaMultiUpdate(in)
}

func (s *DataManageServer) DataAreaIndex(ctx context.Context, in *sys.DataAreaIndexReq) (*sys.DataAreaIndexResp, error) {
	l := datamanagelogic.NewDataAreaIndexLogic(ctx, s.svcCtx)
	return l.DataAreaIndex(in)
}

func (s *DataManageServer) DataAreaMultiDelete(ctx context.Context, in *sys.DataAreaMultiDeleteReq) (*sys.Response, error) {
	l := datamanagelogic.NewDataAreaMultiDeleteLogic(ctx, s.svcCtx)
	return l.DataAreaMultiDelete(in)
}

func (s *DataManageServer) UserAreaApplyIndex(ctx context.Context, in *sys.UserAreaApplyIndexReq) (*sys.UserAreaApplyIndexResp, error) {
	l := datamanagelogic.NewUserAreaApplyIndexLogic(ctx, s.svcCtx)
	return l.UserAreaApplyIndex(in)
}

func (s *DataManageServer) UserAreaApplyDeal(ctx context.Context, in *sys.UserAreaApplyDealReq) (*sys.Response, error) {
	l := datamanagelogic.NewUserAreaApplyDealLogic(ctx, s.svcCtx)
	return l.UserAreaApplyDeal(in)
}
