// Code generated by goctl. DO NOT EDIT!

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roleInfoFieldNames          = builder.RawFieldNames(&RoleInfo{})
	roleInfoRows                = strings.Join(roleInfoFieldNames, ",")
	roleInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(roleInfoFieldNames, "`id`", "`createdTime`", "`updatedTime`", "`deletedTime`"), ",")
	roleInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(roleInfoFieldNames, "`id`", "`createdTime`", "`updatedTime`", "`deletedTime`"), "=?,") + "=?"
)

type (
	roleInfoModel interface {
		Insert(ctx context.Context, data *RoleInfo) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RoleInfo, error)
		FindOneByName(ctx context.Context, name string) (*RoleInfo, error)
		Update(ctx context.Context, data *RoleInfo) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRoleInfoModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RoleInfo struct {
		Id          int64        `db:"id"`          // id编号
		Name        string       `db:"name"`        // 角色名称
		Remark      string       `db:"remark"`      // 备注
		CreatedTime time.Time    `db:"createdTime"` // 创建时间
		UpdatedTime time.Time    `db:"updatedTime"` // 更新时间
		DeletedTime sql.NullTime `db:"deletedTime"`
		Status      int64        `db:"status"` // 状态  1:启用,2:禁用
	}
)

func newRoleInfoModel(conn sqlx.SqlConn) *defaultRoleInfoModel {
	return &defaultRoleInfoModel{
		conn:  conn,
		table: "`role_info`",
	}
}

func (m *defaultRoleInfoModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRoleInfoModel) FindOne(ctx context.Context, id int64) (*RoleInfo, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roleInfoRows, m.table)
	var resp RoleInfo
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleInfoModel) FindOneByName(ctx context.Context, name string) (*RoleInfo, error) {
	var resp RoleInfo
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", roleInfoRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleInfoModel) Insert(ctx context.Context, data *RoleInfo) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, roleInfoRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Remark, data.Status)
	return ret, err
}

func (m *defaultRoleInfoModel) Update(ctx context.Context, newData *RoleInfo) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roleInfoRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Remark, newData.Status, newData.Id)
	return err
}

func (m *defaultRoleInfoModel) tableName() string {
	return m.table
}
