// Code generated by goctl. DO NOT EDIT.
// Source: job.proto

package server

import (
	"context"

	"github.com/i-Things/things/src/timedjobsvr/internal/logic/job"
	"github.com/i-Things/things/src/timedjobsvr/internal/svc"
	"github.com/i-Things/things/src/timedjobsvr/pb/job"
)

type JobServer struct {
	svcCtx *svc.ServiceContext
	job.UnimplementedJobServer
}

func NewJobServer(svcCtx *svc.ServiceContext) *JobServer {
	return &JobServer{
		svcCtx: svcCtx,
	}
}

func (s *JobServer) Ping(ctx context.Context, in *job.Request) (*job.Response, error) {
	l := joblogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
